#! /bin/sh

set -eu

x=${1:?missing x component}
y=${2:?missing y component}
z=${3:?missing z component}

python3 - <<- SCRIPT
	x = ${x}
	y = ${y}
	z = ${z}
	magnitude = (x ** 2 + y ** 2 + z ** 2) ** (1/2)
	x /= magnitude
	y /= magnitude
	z /= magnitude
	print(x, y, z, sep=',')
SCRIPT
